#ifndef __PINS_H
#define __PINS_H


#define SET_BIT(port,bit)   (port |=  (1 << bit))
#define CLEAR_BIT(port,bit) (port &= ~(1 << bit))
#define READ_BIT(port,bit)  ((port & (1 << bit)) ? 1 : 0)



/* User interface Buttons */
#define UI_BUTTON_PORT PORTC
#define UI_BUTTON_DDR  DDRC
#define UI_BUTTON_PIN  PINC

#define UI_BUTTON_ARM_PORT PORTC
#define UI_BUTTON_ARM_DDR  DDRC
#define UI_BUTTON_ARM_PIN  PINC
#define UI_BUTTON_ARM_BIT  PC0

#define UI_BUTTON_MODE_PORT PORTC
#define UI_BUTTON_MODE_DDR  DDRC
#define UI_BUTTON_MODE_PIN  PINC
#define UI_BUTTON_MODE_BIT  PC3

/* User interface Knobs */
#define UI_POT_THRESH_PORT PORTC
#define UI_POT_THRESH_DDR  DDRC
#define UI_POT_THRESH_PIN  PINC
#define UI_POT_THRESH_BIT  PC1
#define UI_POT_THRESH_CHANNEL 2

#define UI_POT_DELAY_PORT PORTC
#define UI_POT_DELAY_DDR  DDRC
#define UI_POT_DELAY_PIN  PINC
#define UI_POT_DELAY_BIT  PC2
#define UI_POT_DELAY_CHANNEL 1

/* User interface Jumper */
#define UI_JUMPER_A_CHANNEL 6
#define UI_JUMPER_B_CHANNEL 7

/* User Interface LEDs */
#define UI_LED_PORT PORTD
#define UI_LED_DDR  DDRD
#define UI_LED_PIN  PIND

#define UI_LED_SOUND_GREEN_PORT PORTD
#define UI_LED_SOUND_GREEN_DDR  DDRD
#define UI_LED_SOUND_GREEN_PIN  PIND
#define UI_LED_SOUND_GREEN_BIT  PD2

#define UI_LED_SOUND_RED_PORT PORTD
#define UI_LED_SOUND_RED_DDR  DDRD
#define UI_LED_SOUND_RED_PIN  PIND
#define UI_LED_SOUND_RED_BIT  PD5

#define UI_LED_LIGHT_GREEN_PORT PORTD
#define UI_LED_LIGHT_GREEN_DDR  DDRD
#define UI_LED_LIGHT_GREEN_PIN  PIND
#define UI_LED_LIGHT_GREEN_BIT  PD4

#define UI_LED_LIGHT_RED_PORT PORTD
#define UI_LED_LIGHT_RED_DDR  DDRD
#define UI_LED_LIGHT_RED_PIN  PIND
#define UI_LED_LIGHT_RED_BIT  PD3

#define UI_LED_ARMED_GREEN_PORT PORTD
#define UI_LED_ARMED_GREEN_DDR  DDRD
#define UI_LED_ARMED_GREEN_PIN  PIND
#define UI_LED_ARMED_GREEN_BIT  PD6

#define UI_LED_ARMED_RED_PORT PORTD
#define UI_LED_ARMED_RED_DDR  DDRD
#define UI_LED_ARMED_RED_PIN  PIND
#define UI_LED_ARMED_RED_BIT  PD7

#define UI_LED_MODE_BITMASK ((1 << UI_LED_SOUND_GREEN_BIT) | (1 << UI_LED_SOUND_RED_BIT) | (1 << UI_LED_LIGHT_GREEN_BIT) | (1 << UI_LED_LIGHT_RED_BIT))
#define UI_LED_BITMASK (UI_LED_MODE_BITMASK | (1 << UI_LED_ARMED_GREEN_BIT) | (1 << UI_LED_ARMED_RED_BIT))

/* Data input */
#define SENSOR_SOUND_PORT    PORTC
#define SENSOR_SOUND_DDR     DDRC
#define SENSOR_SOUND_PIN     PINC
#define SENSOR_SOUND_BIT     PC4
#define SENSOR_SOUND_CHANNEL 4

#define SENSOR_LIGHT_PORT    PORTC
#define SENSOR_LIGHT_DDR     DDRC
#define SENSOR_LIGHT_PIN     PINC
#define SENSOR_LIGHT_BIT     PC5
#define SENSOR_LIGHT_CHANNEL 5

/* Trigger outputs */
#define TRIGGER_PORT PORTB
#define TRIGGER_DDR  DDRB
#define TRIGGER_PIN  PINB

#define TRIGGER_SHUTTER_PORT PORTB
#define TRIGGER_SHUTTER_DDR  DDRB
#define TRIGGER_SHUTTER_PIN  PINB
#define TRIGGER_SHUTTER_BIT  PB0

#define TRIGGER_FOCUS_PORT PORTB
#define TRIGGER_FOCUS_DDR  DDRB
#define TRIGGER_FOCUS_PIN  PINB
#define TRIGGER_FOCUS_BIT  PB1

#define TRIGGER_FLASH_PORT PORTB
#define TRIGGER_FLASH_DDR  DDRB
#define TRIGGER_FLASH_PIN  PINB
#define TRIGGER_FLASH_BIT  PB3

#define TRIGGER_IR_PORT PORTB
#define TRIGGER_IR_DDR  DDRB
#define TRIGGER_IR_PIN  PINB
#define TRIGGER_IR_BIT  PB2


#endif